<?php
/**
 * Legacy translation catalog for MyCustomPrint. Keys are auto-generated by
 * PrestaShop's translation tools from $this->l() calls; hand-maintained here
 * since this module ships without the Symfony translation toolchain.
 */

global $_MODULE;
$_MODULE = [];
$_MODULE['<{mycustomprint}prestashop>mycustomprint_0'] = 'Custom Print Studio';
$_MODULE['<{mycustomprint}prestashop>mycustomprint_1'] = 'Quote-request studio for custom-printed products (upload artwork, pick a blank, placement and print method, get a price estimate).';
$_MODULE['<{mycustomprint}prestashop>mycustomprint_2'] = 'Are you sure you want to uninstall? All submitted print requests will be deleted.';
$_MODULE['<{mycustomprint}prestashop>mycustomprint_3'] = 'Please enter a valid notification email address.';
$_MODULE['<{mycustomprint}prestashop>mycustomprint_4'] = 'At least one blank product is required.';
$_MODULE['<{mycustomprint}prestashop>mycustomprint_5'] = 'At least one print method is required.';
$_MODULE['<{mycustomprint}prestashop>mycustomprint_6'] = 'Settings updated.';
